document.writeln("<div class='footer'>")
document.writeln("<div class='col-md-3 footer-left'>")
document.writeln("<div class='f-mov-list'>")
document.writeln("<h4>最新影片</h4>")
document.writeln("<ul>")
document.writeln("<li><a href='now-showing.html'>正在热映</a></li>")
document.writeln("<li><a href='comming-soon.html'>即将上映</a></li>")
document.writeln("<li><a href='celebrities.html'>影视巨星</a></li>")
document.writeln("</ul>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div></div>")
document.writeln("<div class='col-md-3 footer-left'>")
document.writeln("<div class='f-mov-list'>")
document.writeln("<h4>语言</h4>")
document.writeln("<ul>")
document.writeln("<li><a href='movies.html'>英语</a></li>")
document.writeln("<li><a href='movies.html'>国语</a></li>")
document.writeln("<li><a href='movies.html'>韩语</a></li>")
document.writeln("<li><a href='movies.html'>日语</a></li>")
document.writeln("<li><a href='movies.html'>其他语言</a></li>")
document.writeln("</ul>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div> </div>")
document.writeln("<div class='col-md-3 footer-left'>")
document.writeln("<div class='f-mov-list'>")
document.writeln("<h4>帮助</h4>")
document.writeln("<ul>")
document.writeln("<li><a href='site-map.html'>站点地图</a></li>")
document.writeln("<li><a href='feed-back.html'>您的反馈</a></li>")
document.writeln("<li><a href='faq.html'>常见问题解答</a></li>")
document.writeln("<li><a href='terms-and-conditions.html'>条款和条件</a></li>")
document.writeln("<li><a href='privacy-policy.html'>隐私政策</a></li>")
document.writeln("</ul>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div> </div>")
document.writeln("<div class='col-md-3 footer-left'>")
document.writeln("<div class='f-mov-list'>")
document.writeln("<h4>类型</h4>")
document.writeln("<ul>")
document.writeln("<li><a href='movies.html'>动作片</a></li>")
document.writeln("<li><a href='movies.html'>爱情片</a></li>")
document.writeln("<li><a href='movies.html'>喜剧片</a></li>")
document.writeln("<li><a href='movies.html'>成人片</a></li>")
document.writeln("<li><a href='movies.html'>冒险片</a></li>")
document.writeln("<li><a href='movies.html'>经典片</a></li>")
document.writeln("<li><a href='movies.html'>犯罪片</a></li>")
document.writeln("<li><a href='movies.html'>剧情片</a></li>")
document.writeln("<li><a href='movies.html'>伦理片</a></li>")
document.writeln("<li><a href='movies.html'>魔幻片</a></li>")
document.writeln("<li><a href='movies.html'>音乐片</a></li>")
document.writeln("<li><a href='movies.html'>悬疑片</a></li>")
document.writeln("<li><a href='movies.html'>纪录片</a></li>")
document.writeln("<li><a href='movies.html'>惊悚片</a></li>")
document.writeln("</ul>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div> </div>")
document.writeln("<div class='clearfix'></div>")
document.writeln("<div class='col-md-12'>")
document.writeln("<div class='footer-right'>")
document.writeln("<div class='follow-us'>")
document.writeln("<h5 class='f-head'>关注我们</h5>")
document.writeln("<ul class='social-icons'>")
document.writeln("<li><a href='#'><i class='fa fa-facebook'></i></a></li>")
document.writeln("<li><a href='#'><i class='fa fa-twitter'></i></a></li>")
document.writeln("<li><a href='#'><i class='fa fa-youtube'></i></a></li>")
document.writeln("<li><a href='#'><i class='fa fa-pinterest'></i></a></li>")
document.writeln("<li><a href='#'><i class='fa fa-google-plus'></i></a></li>")
document.writeln("<li><a href='#'><i class='fa fa-linkedin'></i></a></li>")
document.writeln("</ul>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div>")
document.writeln("<div class='subscribe'>")
document.writeln("<h5 class='f-head'>订阅我们的邮件通知</h5>")
document.writeln("<input type='text' class='text' value='Enter Email ID' onFocus='this.value = '';'")
document.writeln("onBlur='if (this.value == 'Enter email...') {this.value = 'Enter Email ID';}'>")
document.writeln("<input type='submit' value='submit'>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div>")
document.writeln("<div class='recent_24by7'>")
document.writeln("<a href='support.html'><i class='fa fa-question'></i>24/7 客服服务</a>")
document.writeln("</div>")
document.writeln("<div class='clearfix'></div>")
document.writeln("</div></div>")
document.writeln("<div class='clearfix'></div></div>")
document.writeln("<div class='clearfix'></div> </div>")
document.writeln("<div class='copy-rights text-center'>")
document.writeln("<p>Copyright &copy; 2015.Company name All rights reserved.More Templates <a href='http://www.cssmoban.com/'")
document.writeln("target='_blank' title='模板之家'>模板之家</a>")
document.writeln("Collect from <a href='http://www.cssmoban.com/' title='网页模板' target='_blank'>网页模板</a></p></div> ")