document.writeln("<div class='header-top-strip' id='home'>")
document.writeln("<div class='container'>")
document.writeln("<div class='header-top-left'>")
document.writeln("<p><a href='support.html'>24/7 客服服务</a></p>")
document.writeln("</div>")
document.writeln("<div class='header-top-right'>")
document.writeln("<div class='modal fade'>")
document.writeln("<div class='modal-dialog'>")
document.writeln("<div class='modal-content'>")
document.writeln("<div class='modal-header'>")
document.writeln("<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>")
document.writeln("<h4 class='modal-title'>Modal title</h4>")
document.writeln("</div>")
document.writeln("<div class='modal-body'>")
document.writeln("<p>One fine body&hellip;</p>")
document.writeln("</div>")
document.writeln("<div class='modal-footer'>")
document.writeln("<button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>")
document.writeln("<button type='button' class='btn btn-primary'>Save changes</button>")
document.writeln("</div>")
document.writeln("</div><!-- /.modal-content -->")
document.writeln("</div><!-- /.modal-dialog -->")
document.writeln("</div><!-- /.modal -->")
document.writeln("<!---pop-up-box---->")
document.writeln("<script>")
document.writeln("$(document).ready(function () {")
document.writeln("$('.popup-with-zoom-anim').magnificPopup({")
document.writeln("type: 'inline',")
document.writeln("fixedContentPos: false,")
document.writeln("fixedBgPos: true,")
document.writeln("overflowY: 'auto',")
document.writeln("closeBtnInside: true,")
document.writeln("preloader: false,")
document.writeln("midClick: true,")
document.writeln("removalDelay: 300,")
document.writeln("mainClass: 'my-mfp-zoom-in'")
document.writeln("});")
document.writeln("}); </script>")
document.writeln("<!-- Large modal -->")
document.writeln("<button class='btn btn-primary' data-toggle='modal' data-target='#myModal'>登录</button>")
document.writeln("<div class='modal fade' id='myModal' tabindex='-1' role='dialog' aria-labelledby='myLargeModalLabel'aria-hidden='true'>")
document.writeln("<div class='modal-dialog modal-lg'>")
document.writeln("<div class='modal-content'>")
document.writeln("<div class='modal-header'>")
document.writeln("<button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;")
document.writeln("</button>")
document.writeln("<h4 class='modal-title' id='myModalLabel'>登录/注册</h4>")
document.writeln("</div>")
document.writeln("<div class='modal-body'>")
document.writeln("<div class='row'>")
document.writeln("<div class='col-md-8' style='border-right: 1px dotted #C2C2C2;padding-right: 30px;'>")
document.writeln("<!-- Nav tabs -->")
document.writeln("<ul class='nav nav-tabs'>")
document.writeln("<li class='active'><a href='#Login' data-toggle='tab'>登录</a></li>")
document.writeln("<li><a href='#Registration' data-toggle='tab'>注册</a></li>")
document.writeln("</ul>")
document.writeln("<!-- Tab panes -->")
document.writeln("<div class='tab-content'>")
document.writeln("<div class='tab-pane active' id='Login'>")
document.writeln("<form role='form' class='form-horizontal'>")
document.writeln("<div class='form-group'>")
document.writeln("<label for='email' class='col-sm-2 control-label'>邮箱</label>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<input type='email' class='form-control' id='email1'placeholder='Email'/>")
document.writeln("</div> </div>")
document.writeln("<div class='form-group'>")
document.writeln("<label for='exampleInputPassword1' class='col-sm-2 control-label'>密码</label>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<input type='password' class='form-control'id='exampleInputPassword1' placeholder='password'/>")
document.writeln("</div> </div>")
document.writeln("<div class='row'>")
document.writeln("<div class='col-sm-2'></div>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<button type='submit' class='btn btn-primary btn-sm'>登录</button>")
document.writeln("<a href='javascript:;'>忘记密码?</a>")
document.writeln("</div> </div> </form> </div>")
document.writeln("<div class='tab-pane' id='Registration'>")
document.writeln("<form role='form' class='form-horizontal'>")
document.writeln("<div class='form-group'>")
document.writeln("<label for='email' class='col-sm-2 control-label'>姓</label>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<div class='row'>")
document.writeln("<div class='col-md-3'>")
document.writeln("<select class='form-control'>")
document.writeln("<option>Mr.</option>")
document.writeln("<option>Ms.</option>")
document.writeln("<option>Mrs.</option></select> </div>")
document.writeln("<div class='col-md-9'>")
document.writeln("<input type='text' class='form-control'placeholder='Name'/></div> </div> </div> </div>")
document.writeln("<div class='form-group'>")
document.writeln("<label for='email' class='col-sm-2 control-label'>邮箱</label>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<input type='email' class='form-control' id='email'placeholder='Email'/></div> </div>")
document.writeln("<div class='form-group'>")
document.writeln("<label for='mobile' class='col-sm-2 control-label'>手机号</label>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<input type='email' class='form-control' id='mobile'placeholder='Mobile'/></div> </div>")
document.writeln("<div class='form-group'>")
document.writeln("<label for='password' class='col-sm-2 control-label'>密码</label>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<input type='password' class='form-control' id='password'placeholder='Password'/></div></div>")
document.writeln("<div class='row'>")
document.writeln("<div class='col-sm-2'> </div>")
document.writeln("<div class='col-sm-10'>")
document.writeln("<button type='button' class='btn btn-primary btn-sm'>申请并登录</button>")
document.writeln("<button type='button' class='btn btn-default btn-sm'>取消 </button> </div> </div> </form> </div> </div>")
document.writeln("<div id='OR' class='hidden-xs'>OR </div> </div>")
document.writeln("<div class='col-md-4'>")
document.writeln("<div class='row text-center sign-with'>")
document.writeln("<div class='col-md-12'>")
document.writeln("<h3 class='other-nw'>第三方平台登陆</h3></div>")
document.writeln("<div class='col-md-12'>")
document.writeln("<div class='btn-group btn-group-justified'>")
document.writeln("<a href='#' class='btn btn-primary'>QQ</a> <a href='#'class='btn btn-danger'>微信</a> </div> </div> </div> </div> </div> </div> </div> </div> </div>")
document.writeln("<script>$('#myModal').modal('no'); </script> </div>")
document.writeln("<div class='clearfix'></div> </div> </div>")